spring:
  config:
    activate:
      on-profile: hug  # Add this line!
  ai:
    huggingface:
      api-key: ${HUG_API_KEY}
      chat:
        base-url: https://api-inference.huggingface.co/models/gpt2
        options:
          temperature: 0.7